spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/taskdb?useUnicode=true&serverTimezone=UTC
    username: root
    password: qwerty
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
